// Code generated by protoc-gen-gotemplate
package foo

import (
    "github.com/golang/protobuf/ptypes/timestamp"
)

type Repository interface {
     GetFoo(timestamp *timestamp.Timestamp ) (string,  error)
}