// Code generated by protoc-gen-gotemplate
package company

import (
	"moul.io/protoc-gen-gotemplate/examples/import/output/models/article"
    "moul.io/protoc-gen-gotemplate/examples/import/output/models/common"
)

type Repository interface {
     GetArticle(getarticle *common.GetArticle ) (*company.Article, []*company.Storage,  error)
}







// ------------------------- Public SDK -----------------------------







// GetArticle : proto: missing extension proto: missing extension
func (sdk *Sdk) GetArticle(ctx context.Context, 
  getarticle *article.GetArticle, token, requestID string)(article *article.Article, storages []*article.GetArticleResponse_Storage, err error) {

  out := &pb.GetArticleResponse{}
	_ = out


  return out.Article, out.Storages, nil
 
}

 
 
