// Code generated by protoc-gen-gotemplate
package article

import (
	"github.com/moul/protoc-gen-gotemplate/examples/import/output/models/article"
    "github.com/moul/protoc-gen-gotemplate/examples/import/output/models/common"
)

type Repository interface {
     GetArticle(getarticle *common.GetArticle ) (*article.Article,  error)
}