name: PR

on:
  #pull_request_target:
  pull_request:
    branches: [ master, main ]
  issue_comment:
    types: [ edited ]

jobs:
  preview:
    name: Release-Notes Preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          git fetch --prune --unshallow --tags
      - uses: snyk/release-notes-preview@v1.6.2
        with:
          releaseBranch: master
        env:
          GITHUB_PR_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}